apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webdav.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webdav.labels" . | nindent 4 }}
type: Opaque
stringData:
  BASIC_USERS: {{ .Values.basicAuth.users | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  OIDCCryptoPassphrase: {{ .Values.oauth.cryptoPassphrase | quote }}
  OIDCClientSecret: {{ .Values.oauth.clientSecret | quote }}
