apiVersion: v1
kind: Service
metadata:
  name: {{ include "webdav.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webdav.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "webdav.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
